/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as PreviewAvatarRouteImport } from './routes/preview/avatar'
import { Route as ShopUserIdRouteImport } from './routes/shop/$userId'
import { Route as ApiPublicRevenuecatWebhookRouteImport } from './routes/api/public/revenuecat-webhook'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewAvatarRoute = PreviewAvatarRouteImport.update({
  id: '/preview/avatar',
  path: '/preview/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopUserIdRoute = ShopUserIdRouteImport.update({
  id: '/shop/$userId',
  path: '/shop/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRevenuecatWebhookRoute =
  ApiPublicRevenuecatWebhookRouteImport.update({
    id: '/api/public/revenuecat-webhook',
    path: '/api/public/revenuecat-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/preview/avatar': typeof PreviewAvatarRoute
  '/shop/$userId': typeof ShopUserIdRoute
  '/api/public/revenuecat-webhook': typeof ApiPublicRevenuecatWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/preview/avatar': typeof PreviewAvatarRoute
  '/shop/$userId': typeof ShopUserIdRoute
  '/api/public/revenuecat-webhook': typeof ApiPublicRevenuecatWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/preview/avatar': typeof PreviewAvatarRoute
  '/shop/$userId': typeof ShopUserIdRoute
  '/api/public/revenuecat-webhook': typeof ApiPublicRevenuecatWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/moderation'
    | '/preview/avatar'
    | '/shop/$userId'
    | '/api/public/revenuecat-webhook'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/moderation'
    | '/preview/avatar'
    | '/shop/$userId'
    | '/api/public/revenuecat-webhook'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/moderation'
    | '/preview/avatar'
    | '/shop/$userId'
    | '/api/public/revenuecat-webhook'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  PreviewAvatarRoute: typeof PreviewAvatarRoute
  ShopUserIdRoute: typeof ShopUserIdRoute
  ApiPublicRevenuecatWebhookRoute: typeof ApiPublicRevenuecatWebhookRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/avatar': {
      id: '/preview/avatar'
      path: '/preview/avatar'
      fullPath: '/preview/avatar'
      preLoaderRoute: typeof PreviewAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$userId': {
      id: '/shop/$userId'
      path: '/shop/$userId'
      fullPath: '/shop/$userId'
      preLoaderRoute: typeof ShopUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/revenuecat-webhook': {
      id: '/api/public/revenuecat-webhook'
      path: '/api/public/revenuecat-webhook'
      fullPath: '/api/public/revenuecat-webhook'
      preLoaderRoute: typeof ApiPublicRevenuecatWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminModerationRoute: AdminModerationRoute,
  PreviewAvatarRoute: PreviewAvatarRoute,
  ShopUserIdRoute: ShopUserIdRoute,
  ApiPublicRevenuecatWebhookRoute: ApiPublicRevenuecatWebhookRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
